### ISSUE TITLE
trying to run code please help.

### ISSUE THREAD

**Issue by PiProject716** [mbaker92/RaspPi-Code#2]
Motion Detected
Image Captured
Traceback (most recent call last):
  File "/home/pi/Documents/PythonCode/security.py", line 54, in <module>
    server.login(username,password)
  File "/usr/lib/python3.7/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/lib/python3.7/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.7/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.3 Authentication unsuccessful [BYAPR08CA0012.namprd08.prod.outlook.com]')

**Comment by mbaker92** [comment]
The errors look like they deal with the email provider and username and password authentication.

The fix depends on the email provider you are using and if your Username and Password are correct. The example I have in this repository uses a Microsoft account (like hotmail). 

 You have to change line 57 to reflect your email provider.
`	   server = smtplib.SMTP('smtp-mail.outlook.com:587')` 

Like a Gmail account would have something like
`         server = smtplib.SMTP('smtp.gmail.com', 587)`

For a Gmail account, you also have to turn on Less Secure Apps in your Google Account to get it to work.
